### ISSUE TITLE
Remarques sur l'onget "A propos"

### ISSUE THREAD

**Issue by jdenes** [psorianom/pseudo_app#3]
Remarque sur la forme : tu as pas moyen de mettre le texte sur toute la largeur de la fenêtre, et pas juste dans la colonne de gauche ?

> La pseudonymisation en quelque mots

Peut-être remplacer par "Qu'est-ce-que la pseudonymisation ?", pour que tous les titres soient des questions.

> est une obligation légale qui s’impose aux administrations

Mathilde m'a fait corriger ce passage dans le guide parce qu'il y a quelques exceptions : j'ai remplacé par "est **généralement une obligation** qui s’impose..."

> Afin de faciliter l'ouverture au grand public

Remplacer par "Afin de faciliter l'ouverture au grand public des **documents administratifs sous forme de texte libre et contenant des données personnelles**" (tu ne dis jamais avant de quel type de documents on parle)

> Cette démo, l'API, et la guide pseudonymisation (où ous pouvez trouver beaucoup plus d'informations) font partie des outils mutuaisables du Lab IA d'Etalab.

Je propose : "Cette démo, l'API **sur laquelle elle s'appuie**, et **le** guide **dans lequel vous trouverez plus d'informations sur la démarche** font partie des outils **mutualisés développés par** le Lab IA d'Etalab.

> La pseudonymisation peut être vu 

"peut être **vue**"

>  Cette démo utilise une approche de ce type, c'est-à-dire, nous avons entraîné un modèle en utilisant des décisions de justice annotées

"Cette démo utilise une approche de ce type : nous avons entraîné un modèle **de REN** en utilisant des décisions de justice annotées"

> annotées indirectement

C'est pas clair très ce que tu veux dire par "indirectement" ?

> Utiliser cette démo

Peut-être remplacer par "Que contient cette démo ?", ça correspond mieux à ce que tu dis ensuite

> La quantité des documents annotés à la main a une certaine relation avec la qualité de l'annotation automatique

Peut-être le formuler dans l'autre sens : "La qualité de la reconnaissance automatique d'entités est directement liée à la quantité de documents annotés à la main"

**Comment by psorianom** [comment]
perfect! J'ai pris tes recommandations.
Oui, j'ai ajouté une inication qu'on utilise des données du CdE.
Indirectement annotée, j'ai expliqué un peu plus. Je veux dire que les annotations ne proviennent pas d'une campagne d'annotation.
