### ISSUE TITLE
Remarque sur "Pseudonymisez un document"

### ISSUE THREAD

**Issue by jdenes** [psorianom/pseudo_app#4]
- Il n'y a pas de message d'erreur quand tu load un doc de plus de 100Ko. Peut-être en ajouter un, sinon on ne comprend pas pourquoi il ne se passe rien.

- Éventuellement mettre un lien sur "lancez le texte exemple en cliquant ici", sinon on ne comprend pas que c'est cliquable (la souris ne passe pas en doigt cliquable)

- Le doc taggé et pseudonymisé ensuite c'est super bien fait !!

**Comment by psorianom** [comment]
Merci ! oui, je vais ajouter une indication ! (En général, si il y a une erreur de n'importe quel type, je n'affiche pas aucun message :1st_place_medal: ) 
À corriger :)

**Comment by psorianom** [comment]
J'ai fait un autre issue pour ton premier point.

**Comment by pedevineau** [comment]
Merged with #8
