### ISSUE TITLE
Remarques sur "Volume des données annotées"

### ISSUE THREAD

**Issue by jdenes** [psorianom/pseudo_app#6]
Sur le titre : "Volume **de** données annotées" c'est plus clean mais franchement c'est pas important

> est un premier pas lors du lancement

Je pense que tu veux dire : "est une première étape indispensable lors..."

> un aperçu sur l'impact du volume

un aperçu **de** l'impact

> les annotations faites par huit modèles différents sur la même décision de justice

au lieu de "annotations faites" j'utiliserais peut-être "les résultats obtenus", pour mieux distinguer l'annotation **humaine** et le résultat de l'algo

> Ces modèles varient par rapport à la taille du corpus d'entraînement utilisé

"La différence entre ces modèles est la taille du corpus utilisé pour les entraîner"

>  c'est mieux d'avoir autant de données annotées que possible

"il est préférable de disposer d'autant de données annotées que possible"

Je trouve que cet onglet est vraiment hyper intéressant et super bien présenté, bravo !

**Comment by psorianom** [comment]
super merci! je les ai appliqué.
