### ISSUE TITLE
Remarques sur "API Stats"

### ISSUE THREAD

**Issue by jdenes** [psorianom/pseudo_app#7]
> Derrière cette dèmo il tourne une API qui fait le travail.

"Derrière cette **démo**, une API réalise la pseudonymisation des exemples que vous lui soumettez."

> Requêtes conll
> Requêtes pseudonymized
> Requêtes tagged

Je sais pas si c'est vraiment important, c'est surtout pour nous j'imagine mais on ne comprend pas vraiment ce que c'est ces trois catégories !

**Comment by psorianom** [comment]
C'est noté ! 
Oui, j'ai hésité à ajouter ces stats qui sont très spécifiques et pas vraiment importantes :/ 
Je vais les enlever.
