### ISSUE TITLE
Support du format .odt?

### ISSUE THREAD

**Issue by bzg** [psorianom/pseudo_app#9]
En lisant [ce commentaire](https://www.nextinpact.com/brief/etalab-propose-un-outil-open-source-de-pseudonymisation-12659.htm#/comment/6209430) je comprends entre les lignes que le format `.odt` est partiellement supporté.

Si c'est bien le cas, peut-on le documenter dans le `README` ou ailleurs?

Que faudrait-il pour le supporter complètement?

**Comment by psorianom** [comment]
Salut @bzg,
Désole pour le retard. J'ai regardé un peu et selon mes tests, l'outil gère les odt. Néanmoins, je n'ai pas ajouté cette extension à la légende que je montre. 
Sinon, il faudrait alors trouver un `odt` qui n'est pas traité correctement.

**Comment by bzg** [comment]
Merci @psorianom pour le retour.

Si je comprends bien, le plus raisonnable est de documenter le support d'`odt` (dans la légende et peut-être ailleurs) tout en signalant que ce support n'est peut-être pas aussi complet que pour les autres formats, en demandant de renvoyer des rapports d'erreur si quelqu'un constate que ce n'est pas le cas ?

Je ne suis pas sûr de voir où modifier le code pour la documentation, si c'est plus court pour toi de me donner des indications n'hésite pas - sinon it's in your hands :)

**Comment by psorianom** [comment]
Tout à fait, je vais ajouter le support `odt` dans la légende.  Pour la question signalement, je crois que je vais laisser les utilisateurs passer par notre contact mail ou de faire un issue.

J'avoue que c'est plus rapide pour moi de le faire. C'est par ici en tout cas: https://github.com/etalab-ia/pseudo_app/blob/3197e203c731c77333944988d9d36038915b6b68/pseudo_app/components/tab_upload.py#L30

**Comment by bzg** [comment]
Hello @pedevineau, je ne suis pas sûr de voir dans quel commit cela a été implémenté ? Ou bien tu fais juste du ménage ?
